#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# Siempre Sales Force — Daily Morning Brief Pipeline
# Runs on Optimus via cron at 7:15 AM (after daily_run.sh at 7:00)
#
# Flow: Vault data → Market agent analysis → Director rollup → Brief
# Output: Morning brief saved to Google Drive + CIO notified
# ═══════════════════════════════════════════════════════════════

set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SWARM_DIR="$(dirname "$SCRIPT_DIR")"
LOG_DIR="$SWARM_DIR/data/sales-force/logs"
BRIEF_DIR="$SWARM_DIR/data/sales-force/briefs"
DRIVE_SALES="/Users/optimus/Library/CloudStorage/GoogleDrive-alex@siempretequila.com/Shared drives/Optimus/Sales Force"
DATE=$(date +%Y-%m-%d)
TIMESTAMP=$(date +%Y-%m-%dT%H:%M:%S)

mkdir -p "$LOG_DIR" "$BRIEF_DIR"

echo "[$TIMESTAMP] Daily Sales Brief Pipeline starting..." | tee -a "$LOG_DIR/pipeline.log"

# ─────────────────────────────────────────────
# STEP 1: Check vault health
# ─────────────────────────────────────────────
echo "[$TIMESTAMP] Step 1: Checking vault health..."
VAULT_STATUS=$(curl -s --connect-timeout 5 http://localhost:8090/health 2>/dev/null || echo '{"status":"down"}')
VAULT_OK=$(echo "$VAULT_STATUS" | python3 -c "import sys,json; print(json.load(sys.stdin).get('status','down'))" 2>/dev/null || echo "down")

if [ "$VAULT_OK" != "ok" ]; then
    echo "[$TIMESTAMP] WARN: Vault is down. Brief will use memory-based context only." | tee -a "$LOG_DIR/pipeline.log"
fi

# ─────────────────────────────────────────────
# STEP 2: Pull market summaries from vault
# ─────────────────────────────────────────────
echo "[$TIMESTAMP] Step 2: Pulling market data from vault..."
SUMMARY=$(curl -s http://localhost:8090/summary 2>/dev/null || echo '{}')
VARIANCE=$(curl -s http://localhost:8090/forecasts/variance 2>/dev/null || echo '{"variance":[]}')

# Extract key metrics
python3 -c "
import json, sys

summary = json.loads('$SUMMARY'.replace(\"'\", '\"') if '$SUMMARY' else '{}')
variance_raw = open('/dev/stdin').read() if False else ''

# Pull from vault variance endpoint
import urllib.request
try:
    resp = urllib.request.urlopen('http://localhost:8090/forecasts/variance', timeout=10)
    variance_data = json.loads(resp.read())
except:
    variance_data = {'variance': []}

rows = variance_data.get('variance', [])

# Aggregate by market for current month
from collections import defaultdict
import datetime
current_month = datetime.date.today().strftime('%Y-%m')
prev_month = (datetime.date.today().replace(day=1) - datetime.timedelta(days=1)).strftime('%Y-%m')

markets = defaultdict(lambda: {'target': 0, 'actual': 0})
for r in rows:
    if r.get('period') == prev_month and r.get('sku') is None and r.get('actual') is not None:
        m = r['market']
        markets[m]['target'] = r['target']
        markets[m]['actual'] = r['actual']

# Score each market
results = []
total_target = 0
total_actual = 0
for m, d in sorted(markets.items(), key=lambda x: -(x[1].get('actual', 0))):
    pct = (d['actual']/d['target']*100) if d['target'] > 0 else 0
    status = 'GREEN' if pct >= 95 else 'YELLOW' if pct >= 70 else 'RED'
    results.append({'market': m, 'target': d['target'], 'actual': d['actual'], 'pct': pct, 'status': status})
    total_target += d['target']
    total_actual += d['actual']

brief = {
    'date': '$DATE',
    'period': prev_month,
    'national': {
        'target': total_target,
        'actual': total_actual,
        'pct': (total_actual/total_target*100) if total_target > 0 else 0
    },
    'markets': results,
    'red_count': sum(1 for r in results if r['status'] == 'RED'),
    'yellow_count': sum(1 for r in results if r['status'] == 'YELLOW'),
    'green_count': sum(1 for r in results if r['status'] == 'GREEN'),
    'ontario': summary.get('ontario', {}),
    'ar': summary.get('ar', {}),
}

with open('$BRIEF_DIR/brief-$DATE.json', 'w') as f:
    json.dump(brief, f, indent=2)

print(f'Brief data saved: {len(results)} markets, {brief[\"red_count\"]} RED / {brief[\"yellow_count\"]} YELLOW / {brief[\"green_count\"]} GREEN')
" 2>&1 | tee -a "$LOG_DIR/pipeline.log"

# ─────────────────────────────────────────────
# STEP 3: Generate morning brief markdown
# ─────────────────────────────────────────────
echo "[$TIMESTAMP] Step 3: Generating morning brief..."
python3 -c "
import json, datetime

with open('$BRIEF_DIR/brief-$DATE.json') as f:
    brief = json.load(f)

lines = []
lines.append('# Siempre Spirits — Morning Sales Brief')
lines.append(f'**{datetime.date.today().strftime(\"%A, %B %d, %Y\")}** | Auto-generated by Sales Force Pipeline')
lines.append('')

# The Number
n = brief['national']
if n['target'] > 0:
    lines.append('## The Number')
    lines.append(f'**{n[\"actual\"]:,.0f} cases** last month vs **{n[\"target\"]:,.0f} target** ({n[\"pct\"]:.1f}%)')
    lines.append('')

# Health Overview
lines.append('## Health Overview')
lines.append(f'| RED | YELLOW | GREEN |')
lines.append(f'|:---:|:------:|:-----:|')
lines.append(f'| {brief[\"red_count\"]} | {brief[\"yellow_count\"]} | {brief[\"green_count\"]} |')
lines.append('')

# RED Markets
reds = [m for m in brief['markets'] if m['status'] == 'RED']
if reds:
    lines.append('## Needs Attention (RED)')
    for m in reds[:10]:
        lines.append(f'- **{m[\"market\"].title()}**: {m[\"actual\"]:,.0f} vs {m[\"target\"]:,.0f} ({m[\"pct\"]:.0f}%)')
    lines.append('')

# GREEN Markets
greens = [m for m in brief['markets'] if m['status'] == 'GREEN']
if greens:
    lines.append('## On Track (GREEN)')
    for m in greens:
        lines.append(f'- **{m[\"market\"].title()}**: {m[\"actual\"]:,.0f} vs {m[\"target\"]:,.0f} ({m[\"pct\"]:.0f}%)')
    lines.append('')

# Ontario LCBO
ont = brief.get('ontario', {})
if ont:
    lines.append('## Ontario (LCBO Live)')
    bottles = ont.get('total_bottles', 'n/a')
    stores = ont.get('total_stores', 'n/a')
    lines.append(f'{bottles} bottles across {stores} stores')
    lines.append('')

# AR
ar = brief.get('ar', {})
if ar:
    overdue = ar.get('total_overdue', 0)
    if overdue > 0:
        lines.append('## AR Alert')
        lines.append(f'Total overdue: \${overdue:,.2f}')
        lines.append('')

md = chr(10).join(lines)
with open('$BRIEF_DIR/morning-brief-$DATE.md', 'w') as f:
    f.write(md)

print('Morning brief generated')
print(md[:500])
" 2>&1 | tee -a "$LOG_DIR/pipeline.log"

# ─────────────────────────────────────────────
# STEP 4: Notify CIO
# ─────────────────────────────────────────────
echo "[$TIMESTAMP] Step 4: Notifying CIO..."
RED_COUNT=$(python3 -c "import json; print(json.load(open('$BRIEF_DIR/brief-$DATE.json'))['red_count'])" 2>/dev/null || echo "?")
GREEN_COUNT=$(python3 -c "import json; print(json.load(open('$BRIEF_DIR/brief-$DATE.json'))['green_count'])" 2>/dev/null || echo "?")

curl -s -X POST http://localhost:8100/cio/report \
  -H 'Content-Type: application/json' \
  -d "{
    \"session_id\": \"optimus-daily-sales-brief\",
    \"platform\": \"optimus-cron\",
    \"device\": \"optimus\",
    \"agent\": \"sales-pipeline\",
    \"events\": [{\"type\": \"completion\", \"summary\": \"Daily morning brief generated. $RED_COUNT RED / $GREEN_COUNT GREEN markets.\", \"tags\": [\"daily-brief\", \"sales\", \"automated\"], \"importance\": 6}],
    \"context_updates\": [{\"key\": \"last_morning_brief\", \"value\": \"$DATE\"}]
  }" 2>/dev/null || echo "CIO notification failed (non-critical)"

echo "[$TIMESTAMP] Pipeline complete." | tee -a "$LOG_DIR/pipeline.log"
