#!/usr/bin/env python3
"""
Populate the Georgia state folder on Google Drive with organized intel.
Creates .docx files in each subfolder from mined data sources.
"""

from docx import Document
from docx.shared import Pt, RGBColor
import os

DRIVE_GA = "/Users/alexl/Library/CloudStorage/GoogleDrive-alex@siempretequila.com/Shared drives/Optimus/Sales Force/Georgia"


def make_doc(title, sections):
    """Create a .docx with title and sections list of (heading, body) tuples."""
    doc = Document()
    doc.add_heading(title, level=0)
    doc.add_paragraph(f"Auto-generated by Siempre AI Sales Force | Source: Gmail, Granola, Google Drive")
    doc.add_paragraph("")
    for heading, body in sections:
        doc.add_heading(heading, level=2)
        if isinstance(body, list):
            for item in body:
                doc.add_paragraph(item, style='List Bullet')
        else:
            doc.add_paragraph(body)
    return doc


def save(doc, subfolder, filename):
    path = os.path.join(DRIVE_GA, subfolder, filename)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    doc.save(path)
    print(f"  Created: {subfolder}/{filename} ({os.path.getsize(path):,} bytes)")


# ═══════════════════════════════════════════════
# PRICING
# ═══════════════════════════════════════════════

doc = make_doc("Georgia Pricing — Current & Historical", [
    ("Current Everyday Pricing (Effective April 1, 2026)",
     "Confirmed March 18-19, 2026 between David Benson (UDIGA) and Alex Lacroix."),
    ("Plata — On-Premise",
     ["Full List: $35.99", "Bottle 1: $28.99", "Cocktail: $26.99", "Manager Deal: $25.99"]),
    ("Plata — Off-Premise",
     ["1 case: $34.38", "3 case: $31.99"]),
    ("Reposado — On-Premise",
     ["Full List: $43.99", "Bottle 1: $33.99", "Cocktail: $30.99", "Manager Deal: $28.99"]),
    ("Reposado — Off-Premise",
     ["1 case: $41.59", "3 case: $35.99"]),
    ("UDIGA Margin Structure (Confirmed)",
     ["Plata margins across deal levels: 35.4%, 32.4%, 28.0%, 28.1%, 26.0%, 30.0%, 27.0%",
      "Reposado margins across deal levels: 39.6%, 36.1%, 28.0%, 27.7%, 26.7%, 28.0%, 27.0%",
      "Floor: ~26-27% at deepest deals"]),
    ("Pricing History",
     ["March 2, 2026: Alex sent updated pricing sheets to David Benson acknowledging 'pricing got ahead of the market'",
      "Target SRP reset: Plata $39.99-$44.99, Reposado $44.99-$54.99",
      "January 2026 (Granola): Revised margin structure — Standard 30% (up from 26.5-27%), On-premise 31%, Cocktail 28%, Deep discount 27% minimum",
      "No tier pricing or channel differentiation — one price for all"]),
    ("Cocktail Program Strategy (from Granola)",
     ["Target FOB: $27.99 for cocktail accounts",
      "$28 price point identified as customer acceptance threshold",
      "Focus on 15-20 lighthouse accounts to influence broader market",
      "Similar successful programs running with 2-3 bourbon brands at UDIGA",
      "Free goods preferred over tiered pricing by retailers"]),
])
save(doc, "Pricing", "GA Pricing — Current & Historical.docx")


# ═══════════════════════════════════════════════
# PROGRAMS
# ═══════════════════════════════════════════════

doc = make_doc("Georgia Programs — Active & Planned", [
    ("The Agave Program 2026 (ACTIVE)",
     ["Status: LIVE as of April 1, 2026",
      "Duration: 16 weeks (April 1 – ~July 22, 2026)",
      "Approved: March 13, 2026 by Alex Lacroix",
      "Source: Winfred Westbrook email with supplier letter attachment",
      "Alex response: 'We love it. Let's get back on the radar!'",
      "Attachment on file: 'The Agave Program - Supplier Letter - 2026.docx'"]),
    ("April–May Free Goods Promotions (ACTIVE)",
     ["Status: Approved March 19 by Alex. 100% on Siempre.",
      "Off-Premise: Buy 3 cases, get 2 bottles free",
      "Off-Premise: Buy 5 cases, get 1 case free",
      "On-Premise: Spirit list/cocktail menu — buy 1 case, get 1 bottle free",
      "Note from Alex: 'Pricing was built for deal levels OR free goods (one or the other) permanent. BUT let's regain some distro. Approved for April-May.'"]),
    ("Savannah Supplier Tradeshow",
     ["Originally planned for April 1, 2026",
      "Justin Israel (March 17): 'It will not be April 1st. You will receive an email as soon as we have a date.'",
      "Nimpha registered interest; awaiting confirmed date",
      "Status: PENDING — date TBD"]),
    ("Brand Ambassador Program",
     ["UDIGA has brand ambassador program (from Granola notes)",
      "Two candidates identified",
      "Status: In discussion"]),
])
save(doc, "Programs", "GA Programs — Active & Planned.docx")


# ═══════════════════════════════════════════════
# CONTACTS
# ═══════════════════════════════════════════════

doc = make_doc("Georgia Contacts — UDIGA Organization", [
    ("Leadership",
     ["Winfred Westbrook — General Manager, Craft Spirits | wwestbrook@udiga.com | (770) 309-8547",
      "Justin Israel — Fine Wine & Craft Spirits Sales Manager | jisrael@udiga.com | (404) 520-2247",
      "David Benson — CSS GM of Spirits / Pricing | dbenson@udiga.com",
      "Jenny Brown — (CC'd on pricing) | jbrown@udiga.com"]),
    ("On-Premise Team (7 reps)",
     ["Chris McNeill | cmcneill@udiga.com | (404) 673-0869",
      "Janelle McDonald | janellem@udiga.com | (404) 909-0207",
      "Jessica Hamlin | jhamlin@udiga.com | (404) 886-9796",
      "Julia Steinem | jsteine@udiga.com | (470) 829-2409",
      "Jeff Burch | jburch@udiga.com | (404) 372-6905",
      "Elena Gilbert | egilbert@udiga.com | (678) 595-8804"]),
    ("IR / Retail Team (3 reps)",
     ["Sara Ross | SaraRoss@udiga.com | (404) 408-4454",
      "Tanya Lawson | TLawson@udiga.com | (404) 518-4669",
      "Steve Harvill | SHarvill@udiga.com | (770) 843-9443"]),
    ("Savannah Region (2 reps)",
     ["Danny Skalak | dskalak@udiga.com | (912) 324-9577",
      "Diane Biggs | dbiggs@udiga.com | (912) 441-7444"]),
    ("Operations / Samples (from recent emails)",
     ["Margaret Wehr | mwehr@udiga.com — sample requests (April 2026)",
      "Ankia Smith | asmith@udiga.com — CC'd on sample coordination",
      "Benjamin Drolette | bdrolette@udiga.com — CC'd on sample coordination",
      "John Sullivan | jsullivan@udiga.com — CC'd on sample coordination"]),
    ("Siempre Team for GA",
     ["Alex Lacroix (Owner) | alex@siempretequila.com | 613-513-5382",
      "Monica Sanita (COO) | monica@siempretequila.com — handles sample approvals, vendor forms",
      "Nimpha Abalorio (Admin) | nimpha@siempretequila.com — scheduling, follow-ups"]),
])
save(doc, "Contacts", "GA Contacts — UDIGA Organization.docx")


# ═══════════════════════════════════════════════
# CORRESPONDENCE (Key Email Thread Summaries)
# ═══════════════════════════════════════════════

doc = make_doc("Georgia Correspondence — Key Email Threads", [
    ("March 19, 2026: Pricing Confirmed + Program Approved",
     ["Thread: 'Georgia Pricing Update — Plata & Reposado'",
      "Parties: Alex ↔ David Benson, CC: Justin Israel, Winfred Westbrook, Nimpha, Jenny Brown",
      "Outcome: New everyday pricing confirmed. Free goods promos approved for April-May.",
      "Alex: 'Pricing confirmed! Let's regain some distro and get after it.'",
      "Alex asked Justin: 'Could I get in front of the broader team in late this month or first thing April?' — response pending"]),
    ("March 13, 2026: Agave Program Approved",
     ["Thread: 'The Agave Program - Supplier Letter - 2026'",
      "From: Winfred Westbrook → Alex",
      "Outcome: Alex approved same day. 'We love it. Let's get back on the radar!'",
      "Attachment: supplier letter .docx on file"]),
    ("March 9, 2026: CBS Team Meeting",
     ["Justin Israel coordinated Nimpha's Zoom slot at 9:45 for CBS team meeting",
      "Demonstrates active relationship cadence"]),
    ("March 4, 2026: Margin Correction",
     ["Alex to David Benson: 'Fellas, I glitched on the margin. Topped up the DAs to keep you decent.'",
      "Plata margins: 35.4% → 26.0% across deal levels",
      "Reposado margins: 39.6% → 26.7% across deal levels",
      "Shows collaborative pricing negotiation dynamic"]),
    ("April 3, 2026: Sample Request Coordination",
     ["Thread: 'United Distributors Sample Request'",
      "Margaret Wehr (UDIGA) → Monica → Alex",
      "Monica approved 2 sample bottles",
      "Established that sample requests go directly to Monica going forward",
      "Shows new contacts entering the relationship (Margaret, Ankia, Benjamin, John)"]),
])
save(doc, "Correspondence", "GA Key Email Threads.docx")


# ═══════════════════════════════════════════════
# MEETING NOTES
# ═══════════════════════════════════════════════

doc = make_doc("Georgia Meeting Notes — From Granola", [
    ("January 2026: Georgia Pricing & Strategy Session",
     ["Source: Granola meeting note #63",
      "URL: https://notes.granola.ai/d/a53e9d71-d7fa-4019-864c-9e95d3a4f473",
      "",
      "Key Decisions:",
      "• Revised margin structure: Standard 30%, On-premise 31%, Cocktail 28%, Deep discount 27% min",
      "• No tier pricing or channel differentiation — one price for all",
      "• Target FOB $27.99 for cocktail accounts ($28 = customer acceptance threshold)",
      "• Focus on 15-20 lighthouse accounts to influence broader market",
      "• Free goods preferred over tiered pricing by retailers",
      "• Brand ambassador program discussed — two candidates identified",
      "• Q2 target launch timeline",
      "• Savannah supplier trade show planned April/May",
      "",
      "Action Items:",
      "• Pricing sheet to be shared with Justin and Winfred for review",
      "• Updated sales roster needed for founder outreach",
      "• Calendar coordination for Savannah trade show"]),
])
save(doc, "Meeting Notes", "GA Meeting Notes — Granola.docx")


# ═══════════════════════════════════════════════
# REPORTS
# ═══════════════════════════════════════════════

doc = make_doc("Georgia Market Reports — Performance Data", [
    ("Q1 2026 Depletion Performance (from Data Vault)",
     ["January: 43.5 cases vs 130 target (33.5%) — BEHIND",
      "February: 52.5 cases vs 142 target (37.0%) — BEHIND",
      "March: 49.0 cases vs 170 target (28.8%) — BEHIND",
      "Q1 Total: 145 cases vs 442 target (32.8%) — CRITICAL RED",
      "Annual Target: 1,853 cases (A Market tier)",
      "Annualized Run Rate: ~580 cases → 31% of annual target"]),
    ("6-Year Historical (from VIP iDig / Foundation)",
     ["GA Total 6-Year Cases: 3,398.83",
      "6-Year Did-Buys: 2,308 off-premise outlets",
      "YTD 2025 vs 2024: -81% YoY decline (439 vs 2,308 cases)",
      "This is the single largest YoY collapse in the portfolio"]),
    ("SKU Mix Analysis (Q1 2026)",
     ["Plata: ~60 cases (41% of mix — target 56%) — UNDER, should lead",
      "Reposado: ~70 cases (48% of mix — target 30%) — OVER, servicing not acquiring",
      "Anejo: ~15 cases (10% of mix — target 8%) — Acceptable",
      "Core SKU mix: 100% (no non-core dilution — good)",
      "Diagnosis: Repo-heavy = retention posture, not growth. New doors open on Plata."]),
    ("Account Erosion (from Dossier)",
     ["8 of top 10 accounts declined 80-100% in 2025",
      "Tower Beer & Wine: 43 cases → 8 cases",
      "4 accounts went to zero entirely",
      "Average throughput: 1.6 cases/account/quarter"]),
    ("Health Score",
     ["Market Grade: A (Top 6)",
      "Overall: RED",
      "% to Target: RED (32.8%)",
      "Reorder Rate: Not available (needs iDig pull)",
      "Pipeline Coverage: Not available",
      "Core SKU Mix: YELLOW (Repo overweight)",
      "Spend per Case: Not available"]),
])
save(doc, "Reports", "GA Market Performance Report.docx")


# ═══════════════════════════════════════════════
# COMPLIANCE
# ═══════════════════════════════════════════════

doc = make_doc("Georgia Compliance — Regulatory Reference", [
    ("State Classification",
     ["Structure: License State (Open State)",
      "Distribution Model: Private distribution",
      "Switching-Risk Flag: Standard (non-franchise)",
      "Region: South"]),
    ("Key Compliance Watchpoints",
     ["Confirm supplier registration with GA ABC",
      "Brand/label approval compliance",
      "Sample and POS material restrictions (may vary by county/municipality)",
      "Local promotional restriction rules (county & city ordinances apply)",
      "County-specific restrictions (some counties more permissive than others)"]),
    ("Trade Practice Rules",
     ["FAA tied-house provisions apply",
      "Custom incentives to retailers = compliance review required",
      "Display pay arrangements = escalation required",
      "Retailer service offers = legal sign-off needed",
      "Distributor termination/exception terms = immediate escalation"]),
    ("PBG Compliance Note (March 2026)",
     ["Justin Ashton (PBG Legal) ruled: free goods to distributor = non-compliant per 3-tier interpretation",
      "Approved alternative: temporary FOB discount for promotional purposes",
      "This sets precedent for all GA promotional mechanics going forward",
      "Alex cited prior GA precedent (MHW); PBG rejected"]),
    ("Reference Sources",
     ["Park Street Market Explorer: parkstreet.com/market-explorer/",
      "TTB Trade Practices: ttb.gov/business-central/trade-practices/",
      "Internal: USA Management Sheet 2025, WIP 2025 Control State Pricing Calendar"]),
])
save(doc, "Compliance", "GA Regulatory Reference.docx")


# ═══════════════════════════════════════════════
# GOOGLE DRIVE FILES INDEX
# ═══════════════════════════════════════════════

doc = make_doc("Georgia — Existing Files on Google Drive", [
    ("Files Found in Drive Root (need organizing)",
     ["Georgia - Price Calculator.gsheet — pricing calculator",
      "Georgia Roll Up.xlsx — historical rollup",
      "GA Opportunities 2022.xlsx — 2022 opportunity pipeline",
      "GA Tastings with Trade Lions.xlsx — tasting event data",
      "Package Store Routes - Georgia.gmap — store route map",
      "Where to find Siempre Tequila in Georgia, USA.gmap — retail finder map",
      "GA Market Visit Schedule _ Accounts.xlsx — account visit schedule"]),
    ("Creative Assets (in Downloads/)",
     ["Store Pick Sticker Georgia.jpg — store pick sticker design",
      "Store Pick Sticker Georgia copy.jpg — alternate version",
      "MMGA HAT.psd — Make Mexico Great Again hat design (GA-specific)"]),
    ("Note", "These files are currently in the Drive root or Downloads folder. They should be moved into the Sales Force/Georgia subfolders for clean organization. Moving Google Sheets/Maps requires manual action in the Drive web UI."),
])
save(doc, "", "GA Existing Drive Files Index.docx")


print(f"\n✓ Georgia folder fully populated")
print(f"Total files: {sum(1 for _, _, files in os.walk(DRIVE_GA) for f in files)}")
